name: Refresh EIA Data
on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:
  
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch EIA Data and Save
        run:  |
               ls
               curl -u USER:TOKEN -g 'https://api.eia.gov/v2/electricity/state-electricity-profiles/emissions-by-state-by-fuel/data/?api_key=${{ secrets.EIA_API_KEY }}&facets[fuelid][]=ALL&data[]=co2-rate-lbs-mwh' > data.json
               ls
               git config --local user.email "action@github.com"
               git config --local user.name "github-actions"
               git add --all
               git commit -m "Add changes" -a
               ls
        shell: bash
