name: Refresh EIA Data
on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:
  
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Fetch API Data and Save
        id: saveJSONDetails
        uses: engahmeds3ed/create-json-url@v0.0.1
        with:
          name: "new.json"
          url: "https://api.eia.gov/v2/electricity/state-electricity-profiles/emissions-by-state-by-fuel/data/?api_key=${{ secrets.EIA_API_KEY }}&facets[fuelid][]=ALL&data[]=co2-rate-lbs-mwh"
          dir: '/data/'
