name: Refresh EIA Data
on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:
  
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: actions/checkout@4
        with:
          endpoint: https://api.eia.gov/v2/electricity/state-electricity-profiles/emissions-by-state-by-fuel/data/?api_key=${{secrets.EIA_API_KEY}}&facets[fuelid][]=ALL&data[]=co2-rate-lbs-mwh

      - name: Build and Deploy
        uses: actions/checkout@4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: eia_data # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.
