name: Refresh EIA Data
on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:
  
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      
      - name: Fetch EIA Data and Save
        run:  |
              echo "📡 Fetching Data... 📡"
              curl -u USER:TOKEN -g 'https://api.eia.gov/v2/electricity/state-electricity-profiles/emissions-by-state-by-fuel/data/?api_key=${{ secrets.EIA_API_KEY }}&facets[fuelid][]=ALL&data[]=co2-rate-lbs-mwh' > data.json
              echo "💾 Data Fetched 💾"
              git config --global user.name 'GitHub Actions'
              git config --global user.email 'actions@github.com'
              git add data.json
              git commit -am "Daily EIA Update" --force
              git push
              echo "🎉 Updates Pushed Successfully! 🎉"
        shell: bash
